### ISSUE TITLE
Hitting rate limit after initial login causing 401's

### ISSUE THREAD

**Issue by sirkirby** [sirkirby/unifi-network-rules#15]
## Debug Logging

[x] debug logging is enabled in the configuration.

```yaml
logger:
  default: error
  logs:
    custom_components.unifi_network_rules: debug
```

## Describe the bug

After initial configuration, I see 429 rate limit errors and several 401 errors from subsequent API requests. This should not happen if the login was unsuccessful.

## Expected behavior

If the login fails, this should back off and wait for 429's to clear.

## Home Assistant Logs

Paste the relevant logs from the Home Assistant log file here.
