### ISSUE TITLE
Renaming entities causes integration to become unstable

### ISSUE THREAD

**Issue by RubenVerborgh** [sirkirby/unifi-network-rules#47]
## Debug Logging

[x] debug logging is enabled in the configuration.

Click the "Enable Debug Logging" button in the integration configuration.

or manually add the following to your `configuration.yaml` file:

```yaml
logger:
  default: error
  logs:
    custom_components.unifi_network_rules: debug
```

Then restart Home Assistant.

## Describe the bug

When I change the Entity ID of a traffic rule in the Home Assistant UI, the corresponding kill switch entity disappears. 

## To Reproduce

1. Change the Entity ID of a traffic rule

## Expected behavior

- The kill switch entity remains available

## Home Assistant Logs

Paste or attach the relevant logs from the Home Assistant log file here.
